services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: yesno
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app -d yesno"]
      interval: 3s
      timeout: 3s
      retries: 30

  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: yesno
      POSTGRES_PORT: 5432
      API_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data:
