name: yesno-fortune-app

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: yesno
    ports:
      - "5432:5432"   # 既存Postgresがいれば 5433:5432 に
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d yesno -h 127.0.0.1 -p 5432"]
      interval: 3s
      timeout: 3s
      retries: 30

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      DATABASE_URL: postgres://app:app@db:5432/yesno  # ← これだけでOK
      PORT: 8080                                      # ← server.js は PORT を参照
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/api/health >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -lc "http-server dist -p 5173 -a 0.0.0.0 -P http://api:8080"

volumes:
  db-data:
