services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=yesno
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d yesno"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://app:app@db:5432/yesno
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  web:
    image: node:20-alpine
    working_dir: /app
    environment:
      - VITE_API_BASE=http://localhost:8080
    # ルート直下のフロントを利用
    volumes:
      - ./:/app:cached
    # 初回に依存を入れて build → preview まで実行
    command: sh -c "npm ci && npm run build && npm run preview -- --host --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  db:
